spring.application.name=springSecurityProject2
# Database URL
spring.datasource.url=jdbc:mysql://localhost:3306/kodnest

# Database credentials
spring.datasource.username=root
spring.datasource.password=root

# JDBC Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate (JPA) properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Optional (for better logging)
spring.jpa.properties.hibernate.format_sql=true